// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgAMtk0bLOQPkGiu4zWI35jiAU-VTk4AQ',
    appId: '1:617806389408:web:76769b4dfbb44ca5b0e9c5',
    messagingSenderId: '617806389408',
    projectId: 'safechild-b2460',
    authDomain: 'safechild-b2460.firebaseapp.com',
    storageBucket: 'safechild-b2460.firebasestorage.app',
    measurementId: 'G-9R3S0ZKYCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8X-i6vaGQ3MMqkmYETnw307VQHewXy2w',
    appId: '1:617806389408:android:c342ea070e5cd8cdb0e9c5',
    messagingSenderId: '617806389408',
    projectId: 'safechild-b2460',
    storageBucket: 'safechild-b2460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxQMdHOSfO-G7nrHcEDxGzpr5cUJsqsE',
    appId: '1:617806389408:ios:1df8db45f3732fd1b0e9c5',
    messagingSenderId: '617806389408',
    projectId: 'safechild-b2460',
    storageBucket: 'safechild-b2460.firebasestorage.app',
    iosBundleId: 'com.example.safechild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxQMdHOSfO-G7nrHcEDxGzpr5cUJsqsE',
    appId: '1:617806389408:ios:1df8db45f3732fd1b0e9c5',
    messagingSenderId: '617806389408',
    projectId: 'safechild-b2460',
    storageBucket: 'safechild-b2460.firebasestorage.app',
    iosBundleId: 'com.example.safechild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgAMtk0bLOQPkGiu4zWI35jiAU-VTk4AQ',
    appId: '1:617806389408:web:ad96449ad28c31edb0e9c5',
    messagingSenderId: '617806389408',
    projectId: 'safechild-b2460',
    authDomain: 'safechild-b2460.firebaseapp.com',
    storageBucket: 'safechild-b2460.firebasestorage.app',
    measurementId: 'G-82CF676TYJ',
  );
}
